### PR TITLE
Add new fields to sg-core metric messages

### PR DESCRIPTION
**Pull request by yadneshk**
With changes [1] Ceilometer is now able to include "project_name" and "user_name" fields into it's metrics. These fields are only added when ceilometer has `tenant_name_discovery` config enabled.

This change amends these fields to the outgoing metric messages.

Fixes: #110

[1] https://review.opendev.org/q/topic:enhanced_metrics-stable/wallaby

### CODE REVIEW

**Review by csibbitt — APPROVED** [review]
LGTM!

**Review by leifmadsen — APPROVED** [review]
+1

**Review by vyzigold — APPROVED** [review]

**Comment by yadneshk** [comment]
With these 2 commits, fields `project_name`, `user_name` & `resource_name` are added to metrics.

```
ceilometer_cpu{container="sg-core", counter="cpu", cpu="d3fb814f-bf78-4133-9acc-3f3e38a221b3", endpoint="prom-https", 
project="9fca02c6653e41b09067a9ace53ab24b", project_name="admin", resource="d3fb814f-bf78-4133-9acc-
3f3e38a221b3",resource_name="cirros:instance-00000001", service="default-cloud1-ceil-meter", type="cpu",  
unit="ns",user="89bd630a63fb44a5a4dd084551315a56", user_name="admin", 
vm_instance="1338460c52b26353a527c75a2a1eae2f0342c683fa35ba35e63e7d08"}

ceilometer_network_incoming_bytes{container="sg-core", counter="network.incoming.bytes", endpoint="prom-https", 
network="bytes", project="9fca02c6653e41b09067a9ace53ab24b", project_name="admin", resource="instance-00000001-
d3fb814f-bf78-4133-9acc-3f3e38a221b3-tapeeb377c4-79", resource_name="cirros:tapeeb377c4-79", service="default-cloud1-
ceil-meter", type="incoming", unit="B", user="89bd630a63fb44a5a4dd084551315a56", user_name="admin", 
vm_instance="1338460c52b26353a527c75a2a1eae2f0342c683fa35ba35e63e7d08"}

ceilometer_disk_device_allocation{container="sg-core", counter="disk.device.allocation", disk="allocation", endpoint="prom-
https", project="9fca02c6653e41b09067a9ace53ab24b", project_name="admin", resource="d3fb814f-bf78-4133-9acc-
3f3e38a221b3-vda", resource_name="cirros:instance-00000001", service="default-cloud1-ceil-
meter", type="device", unit="B", user="89bd630a63fb44a5a4dd084551315a56", user_name="admin", vm_instance="1338460c
52b26353a527c75a2a1eae2f0342c683fa35ba35e63e7d08"}
```

**Comment by leifmadsen** [comment]
Just FYI I don't believe the CI failure here has anything to do with the patch. I know Jaromir is looking into this, so hopefully we can get this merged sometime next week.

**Comment by leifmadsen** [comment]
Updated branch with latest CI refactoring in the hopes we can get this merged.

**Pull request merged**
