### PR TITLE
Finish events support

### PR DESCRIPTION
**Pull request by paramite**
- Adds unit tests for events handlers and apps
- Adds log support for elasticsearch app

Depends-On: https://github.com/infrawatch/apputils/pull/16

### CODE REVIEW

**Comment by paramite** [comment]
Lint is lying. I have automated gofmt set in Atom.

  Error: File is not `gofmt`-ed with `-s` (gofmt)
  Error: File is not `gofmt`-ed with `-s` (gofmt)
  Error: File is not `gofmt`-ed with `-s` (gofmt)

ALso unit tests are failing on metrics side, will check tomorrow. Kind of don't understand why it is not showed here: 
https://github.com/paramite/sg-core/actions/runs/659382414

**Comment by paramite** [comment]
Hmmpf: 

[para@localhost sg-core]$ go fmt plugins/handler/events/collectd/*
[para@localhost sg-core]$ go fmt plugins/handler/events/ceilometer/*
[para@localhost sg-core]$ git diff
[para@localhost sg-core]$

**Comment by paramite** [comment]
Unit tests will fail until https://github.com/infrawatch/apputils/pull/16 will be merged. alertmanager app still missing unit tests, this is WIP currently. Please do not merge yet.

**Comment by pleimer** [comment]
Oh I missed that you were tracking logging updates here. I'll close out the other patch I made!

**Comment by vyzigold** [comment]
Looks fine to me.

**Pull request merged**
