### PR TITLE
Add devstack plugin

### PR DESCRIPTION
**Pull request by vyzigold**
This PR adds a devstack plugin. This makes it possible to deploy sg-core in a container while deploying devstack.

Example of working local.conf used while testing this (remove the "jwysogla-devstack") once this is merged. This local.conf will result in a running container with sg-core and ceilometer configured to send metrics to that container:
```
[[local|localrc]]
ADMIN_PASSWORD=secret
DATABASE_PASSWORD=$ADMIN_PASSWORD
RABBIT_PASSWORD=$ADMIN_PASSWORD
SERVICE_PASSWORD=$ADMIN_PASSWORD

CEILOMETER_BACKEND=sg-core

USE_PYTHON3="True"

VERBOSE="True"

VERBOSE_NO_TIMESTAMP="True"

LIBS_FROM_GIT=aodh,ceilometer,cinder,devstack,devstack-gate,dib-utils,diskimage-builder,glance,heat,keystone,neutron,nova,placement,requirements,swift,sg-core

enable_plugin aodh https://opendev.org/openstack/aodh
enable_plugin ceilometer https://opendev.org/openstack/ceilometer refs/changes/87/898087/1
enable_plugin heat https://opendev.org/openstack/heat
enable_plugin sg-core https://github.com/infrawatch/sg-core jwysogla-devstack
```

There is another change, that's worth to mention: https://review.opendev.org/c/openstack/ceilometer/+/898087 That will add support for a sg-core backend to ceilometer as can be seen in the example local.conf

### CODE REVIEW

**Comment by vyzigold** [comment]
Looks like the work is already starting to pay off. I think I can see the same error, which is caught by our CI during my testing in devstack. With the recent rewrite of the TCP publisher in ceilometer, it looks like it fails to properly connect if ceilometer is started before sg-core. Restart of the notification-agent seems to fix the issue. I'll investigate the issue further and propose a fix on the ceilometer side.

**Comment by vyzigold** [comment]
Also another thing. I tested a full devstack deployment using the local.conf mentioned above to test with centos stream 9 and with debian bookworm.

**Comment by yadneshk** [comment]
@vyzigold this looks great! In future it would be nice to curl sg-core for some metrics after we've created some resources on the cloud (images, volumes).

**Comment by vyzigold** [comment]
@yadneshk This is my next step. I have an addition to the telemetry-tempest-plugin almost ready, which makes use of all of this and it queries sg-core.

**Comment by vyzigold** [comment]
Since I mentioned it here. Here is a fix for the ceilometer issue. We should be able to merge it once the ceilometer CI is fixed sometime next week probably. After that the sg-core CI here should start succeeding.
https://review.opendev.org/c/openstack/ceilometer/+/898215

**Comment by jokke-ilujo** [comment]
Gr8 work, thanks a lot Jaromir.

**Review by leifmadsen — APPROVED** [review]
While not familiar with devstack, these changes are self contained and would't cause any sort of regression.

**Comment by csibbitt** [comment]
It's been awhile since I've used devstack. I'm hoping to try this out today; I'll let you know how it goes.

**Comment by csibbitt** [comment]
I followed the instructions and got myself a working devstack with a running sg-core container and a set of ceilometer processes:

```
[stack@stream9 devstack]$ podman ps
CONTAINER ID  IMAGE                              COMMAND     CREATED         STATUS         PORTS       NAMES
3a231c4a1b7a  quay.io/infrawatch/sg-core:latest              30 minutes ago  Up 30 minutes              sg-core

[stack@stream9 devstack]$ ps ax | grep ceil
 248393 ?        Ssl    0:01 ceilometer-polling: master process [/usr/local/bin/ceilometer-polling --polling-namespaces central --config-file /etc/ceilometer/ceilometer.conf]
 248872 ?        Sl     0:01 ceilometer-polling: AgentManager worker(0)
 249237 ?        Ssl    0:01 ceilometer-agent-notification: master process [/usr/local/bin/ceilometer-agent-notification --config-file /etc/ceilometer/ceilometer.conf]
 249581 ?        Sl     0:12 ceilometer-agent-notification: NotificationService worker(0)
 249583 ?        Sl     0:09 ceilometer-agent-notification: NotificationService worker(1)
 249979 ?        Ssl    0:01 ceilometer-polling: master process [/usr/local/bin/ceilometer-polling --polling-namespaces compute --config-file /etc/ceilometer/ceilometer.conf]
 250269 ?        Sl     0:00 ceilometer-polling: AgentManager worker(0)
```

I tried running tempest to get some ceilometer activity, but my VM ran out of storage and OSP is borked. Whoops.

Anyways, I can hit the sg_core instance. 

```
[stack@stream9 devstack]$ curl localhost:3000/metrics
# HELP sg_total_ceilometer_metric_decode_count 
# TYPE sg_total_ceilometer_metric_decode_count counter
sg_total_ceilometer_metric_decode_count{source="SG"} 0
# HELP sg_total_ceilometer_metric_decode_error_count 
# TYPE sg_total_ceilometer_metric_decode_error_count counter
sg_total_ceilometer_metric_decode_error_count{source="SG"} 0
# HELP sg_total_ceilometer_msg_received_count 
# TYPE sg_total_ceilometer_msg_received_count counter
sg_total_ceilometer_msg_received_count{source="SG"} 0
```

I'll try to revive my devstack to see if I can get actual metrics flowing, but for now I'm gonna say this is good since it's headed in the right direction and doesn't break anything.

**Review by csibbitt — APPROVED** [review]

**Comment by vyzigold** [comment]
If you deploy devstack and have some image there (I noticed, there is usually a cirros and fedora image right after I deploy), then ceilometer will start sending metrics about the image size without the need to run anything else. (So just stack.sh and wait enough time). The issue is, that ceilometer needs a restart after stack.sh is finished to work, which is wrong and there is a fix already proposed upstream, which is waiting for CI to work. This is also the reason why the CI doesn't work here.

**Comment by vyzigold** [comment]
I'll wait until the end of the day. If I don't see a change in pyparsing, which is the first step for our CI to start succeeding and if nobody minds me doing this, I'll just merge this. I think we all agreed, that this is an isolated change and it won't break anything.

**Pull request merged**
