### PR TITLE
Move to golang 1.20 (#127)

### PR DESCRIPTION
**Pull request by csibbitt**
* Move to golang 1.20

* Bump golangci-lint to 1.51 for golang 1.20 support

(cherry picked from commit 35d6fbeac82fc3313f8d73bca28cf5fc6f18d5cf)

### CODE REVIEW

**Comment by leifmadsen** [comment]
I'm surprised this wasn't merged as part of the STF 1.5.3 work. Did we not end up importing master to stable-1.5 in 1.5.3? (no other changes?)

**Comment by leifmadsen** [comment]
> I'm surprised this wasn't merged as part of the STF 1.5.3 work. Did we not end up importing master to stable-1.5 in 1.5.3? (no other changes?)

Oh this was only merged 3 weeks ago, which is well after 1.5.3 was tagged. Is there a need to backport this now vs just waiting for STF 1.5.4 and importing master to stable-1.5 at that time?

**Comment by leifmadsen** [comment]
> > I'm surprised this wasn't merged as part of the STF 1.5.3 work. Did we not end up importing master to stable-1.5 in 1.5.3? (no other changes?)
> 
> Oh this was only merged 3 weeks ago, which is well after 1.5.3 was tagged. Is there a need to backport this now vs just waiting for STF 1.5.4 and importing master to stable-1.5 at that time?

Never mind, I found the answer in an email I got 3 mins ago. Thanks!

**Review by leifmadsen — APPROVED** [review]

**Review by vkmc — APPROVED** [review]
LGTM

**Pull request merged**
