### PR TITLE
Move to golang 1.20

### PR DESCRIPTION
**Pull request by csibbitt**
Seems like we could do a bit of DRY optimization here, but search and replace is pretty good these days. :)

DependZ-On: https://github.com/infrawatch/service-telemetry-operator/pull/531

### CODE REVIEW

**Comment by csibbitt** [comment]
The lint tests are exiting with "null"? When I run them locally I do get some errors: https://paste.opendev.org/show/bh0u0wkNYdbsslieTlNb/

I'll need to look closer at these and at the failing CI workflow to figure out what's going on. On yesterday's PR (#126) it at least complained about the new "toolchain" directive in go.mod (not present here) and exited code 3. Not sure if something broke over night, or if the linter just needs a version bump as well.

**Comment by vyzigold** [comment]
Looks like support for golang 1.20 was added in golangci-lint 1.51.0 (we still use 1.50.1). https://github.com/golangci/golangci-lint/blob/0d5efec283c2e8d92f2132b4c3d2d698db6eff7c/CHANGELOG.md?plain=1#L298

**Comment by csibbitt** [comment]
The "local_build" jobs that failed didn't even really start. The one that passed basically proves that this change worked. I'm going to just keep typing recheck. Emma has work that is supposed to improve the stability of these tests here: https://github.com/infrawatch/service-telemetry-operator/pull/531

**Comment by csibbitt** [comment]
recheck

**Comment by csibbitt** [comment]
recheck

**Comment by elfiesmelfie** [comment]
> recheck

You can run your changes against the new CI jobs by using `Depends-On: https://github.com/infrawatch/service-telemetry-operator/pull/531` in the PR description

**Comment by csibbitt** [comment]
recheck

**Comment by csibbitt** [comment]
recheck

**Review by vkmc — APPROVED** [review]
Code looks good, CI failures are not related. Thanks!

**Pull request merged**
