### PR TITLE
Import master to stable-1.5

### PR DESCRIPTION
**Pull request by leifmadsen**
Import master into stable-1.5 in preparation for STF 1.5.3 release.

- Add TCP to the socket transport plugin (#103)
- Move to golang 1.19 (#104)
- Bump github.com/prometheus/client_golang from 1.11.0 to 1.11.1 (#107)
- Specify handler name in handler config error msg (#109)
- Fix integration CI (#113)
- Rewrite integration CI (#117)
- Bump golang.org/x/sys from 0.0.0-20210630005230-0f9fa26af87c to 0.1.0 (#108)
- Bump gopkg.in/yaml.v3 from 3.0.0-20210107192922-496545a6307b to 3.0.0 (#116)
- Added a capability for generating ceilometer messages (#112)
- Add new fields to sg-core metric messages (#111)
- Add devstack plugin (#118)

### CODE REVIEW

**Comment by leifmadsen** [comment]
@vyzigold are these failing tests expected to still be failing?

**Comment by vyzigold** [comment]
Yes, the CI upstream is still blocked. We are waiting for some upstream folks to review and hopefully merge our attempt to downgrade pyparsing (we can't +2 the patch) https://review.opendev.org/c/openstack/requirements/+/898699 . After that it's basically on us (cloudops) to get the required fix in ceilometer merged. So after the downgrade is merged, stuff should start moving pretty fast.

**Comment by leifmadsen** [comment]
> Yes, the CI upstream is still blocked. We are waiting for some upstream folks to review and hopefully merge our attempt to downgrade pyparsing (we can't +2 the patch) https://review.opendev.org/c/openstack/requirements/+/898699 . After that it's basically on us (cloudops) to get the required fix in ceilometer merged. So after the downgrade is merged, stuff should start moving pretty fast.

I'm confused. Aren't the tests here local and unrelated to that patch?

**Comment by leifmadsen** [comment]
> > Yes, the CI upstream is still blocked. We are waiting for some upstream folks to review and hopefully merge our attempt to downgrade pyparsing (we can't +2 the patch) https://review.opendev.org/c/openstack/requirements/+/898699 . After that it's basically on us (cloudops) to get the required fix in ceilometer merged. So after the downgrade is merged, stuff should start moving pretty fast.
> 
> I'm confused. Aren't the tests here local and unrelated to that patch?

Oh actually, I guess it's the issue with the Ceilometer container itself and the patch is for landing into that container which would be pulled into this test? I'm going to ignore the test here then. If everything else looks good, can you mark this PR as approved?

**Comment by vyzigold** [comment]
I looked at the error in the CI. As far as I can tell, it's consistent with the ceilometer issue, for which we already have a fix on review upstream. So there shouldn't be an issue with sg-core, although the CI currently isn't able to test anything regarding the TCP transport.

**Comment by vyzigold** [comment]
> > > Yes, the CI upstream is still blocked. We are waiting for some upstream folks to review and hopefully merge our attempt to downgrade pyparsing (we can't +2 the patch) https://review.opendev.org/c/openstack/requirements/+/898699 . After that it's basically on us (cloudops) to get the required fix in ceilometer merged. So after the downgrade is merged, stuff should start moving pretty fast.
> > 
> > 
> > I'm confused. Aren't the tests here local and unrelated to that patch?
> 
> Oh actually, I guess it's the issue with the Ceilometer container itself and the patch is for landing into that container which would be pulled into this test? I'm going to ignore the test here then. If everything else looks good, can you mark this PR as approved?

The CI here pulls the current ceilometer master. Ceilometer doesn't yet test if the integration between ceilometer and sg-core works, so we managed to break the TCP publisher in ceilometer recently. Once the ceilometer master gets the fix, it'll appear in our CI here right away.

**Review by vyzigold — APPROVED** [review]

**Comment by leifmadsen** [comment]
Thanks @vyzigold !

**Pull request merged**
